version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/var/www
      - node_modules:/var/www/node_modules
    working_dir: "/var/www"
    tty: true
    stdin_open: true
    command: yarn dev
    ports:
      - "3000:3000"
      - "24678:24678"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500
      - WATCHPACK_POLLING=true
      - API_URL=http://host.docker.internal:8081
      - BROWSER_API_URL=http://localhost:8081
      - STORAGE_URL=https://file.meltyblood-typelumina-fan.com
      - SITE_URL=http://localhost:3000
      - SITE_OGP_IMAGE=https://file.meltyblood-typelumina-fan.com/site_image/ogp.jpeg
    networks:
      - nuxt

volumes:
  node_modules:


networks:
  nuxt:
